spring.application.name=BudgetApp

# ?????? ??? ?-Render
server.address=0.0.0.0
server.port=8080

# ????? ???? ??????? ???? (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-twilight-mountain-axuysame.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6lx3yVhYanSX
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????? ????? ?????? ?????? ??????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update