spring.application.name=BudgetApp
# ????? ??? ?????? H2 ?????? ?? ?????? ????? ??????? ???? ??? ????? ??? ????? ??? budget_db
spring.datasource.url=jdbc:h2:file:./budget_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ????? ????? ??????? ?????? ????
spring.jpa.hibernate.ddl-auto=update

# ????? ???? ????? ??? ???? ??????? (?????????)
spring.h2.console.enabled=true