spring.application.name=BudgetApp

# ?????? ??? ?-Render
server.address=0.0.0.0
server.port=8080

# ????? ???? ??????? ???? (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-old-bird-b5vx31i1-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fkKC2DV0lTAp
spring.datasource.driver-class-name=org.postgresql.Driver

# ?????? ????? ?????? ?????? ??????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# ????? ???? ????? ?? ?? ???????? ???? ??????? ????? ??? ????
spring.datasource.hikari.minimum-idle=0

# ???? ????? ???? ???? 15 ????? ?? ???? ??????
spring.datasource.hikari.idle-timeout=15000

# ???? ????????? ????? ???? ?????? ?????? ????
spring.datasource.hikari.max-lifetime=60000